### ISSUE TITLE
Game Crashes With mod

### ISSUE THREAD

**Issue by Thedarkladdy123** [Suff99/ExtraShells#2]
Issue description
Okay, any time i open the game with extra shells, it crashes but if i remove it, the game loads without the other mods enabled
[crash-2024-05-18_18.51.34-client.txt](https://github.com/Jeryn99/ExtraShells/files/15367074/crash-2024-05-18_18.51.34-client.txt)

Steps to reproduce
Install Extra Shells, Fabric API, Tardis Refined, JEI. Then load up game. After game crashes remove ONLY extra shells. Load game and open world

1.20.2 (Latest)

Fabric

Mod Loader version
Various

Tardis Refined version
v2.0

Other relevant versions
Extra Shells Ver: 1.0.2

**Comment by Jeryn99** [comment]
https://github.com/WhoCraft/TardisRefined/issues/280
