### ISSUE TITLE
Shells do not appear in the exterior configuration

### ISSUE THREAD

**Issue by IntellMove** [Suff99/ExtraShells#3]
TARDIS Refined version: 2.0.1
Extra Shells version: 1.0.2

Fabric 0.15.11

Issue: Extra Shells configurations do not show on monitor.

Additional information: Using a server with other mods, (no immersive portals).

https://github.com/Jeryn99/ExtraShells/assets/94828376/e07777d1-7544-4915-9143-98510e03cce0

**Comment by Jeryn99** [comment]
Show me your mods folder

**Comment by IntellMove** [comment]
![image](https://github.com/Jeryn99/ExtraShells/assets/94828376/e0f71b51-a815-41d5-a818-024d16cba11b)

**Comment by IntellMove** [comment]
> Show me your mods folder

![Screenshot 2024-05-24 074433](https://github.com/Jeryn99/ExtraShells/assets/94828376/47c09070-95fa-4724-8654-11d2ac848082)

**Comment by MrQuestion22** [comment]
does not work for me

**Comment by Jeryn99** [comment]
Does this still happen with new updates?

**Comment by Jeryn99** [comment]
Upon further investigation, you are not using the mod correctly
