### ISSUE TITLE
Missing Version 1.20.1

### ISSUE THREAD

**Issue by ErythroCraft** [Suff99/ExtraShells#4]
Hello

Great job. Can you give a version on forge 1.20.1 - 47.3.0 ?

**Comment by Jeryn99** [comment]
Why did you close this before I even replied to it?

**Comment by ErythroCraft** [comment]
@Jeryn99 sorry I think asking is not the right way.
I didn't want to be intrusive.

**Comment by Jeryn99** [comment]
sorted
