### ISSUE TITLE
[Forge1.20.1] Crash on Start

### ISSUE THREAD

**Issue by mrdrewlego** [Suff99/ExtraShells#5]
Attempting to use the forge 1.20.1 mod version with Tardis Refined 2.0.3 causes a crash on startup.
Exception caught during firing event: No model for layer extra_shells:tommy_ext#tommy_ext

Crash Log: https://mclo.gs/ErWSRTh

**Comment by Bonkjumper** [comment]
I have the same issue under the same circumstances and I am running 2.0.4

**Comment by Jeryn99** [comment]
Update
