### ISSUE TITLE
[Forge 1.20.1] Missing class crash

### ISSUE THREAD

**Issue by mrdrewlego** [Suff99/ExtraShells#6]
Attempting to use the extra shells 1.0.5 a crash on startup occurs. 
java.lang.NoClassDefFoundError: mc/craig/software/extra_shells/neoforge/ESModelRegistryImpl

Link to crash log: https://mclo.gs/T9nhJU7

**Comment by Thedarkladdy123** [comment]
I have the same issue!  for both 1.0.4 and 1.0.5!
[crash-2024-07-08_18.19.16-client.txt](https://github.com/user-attachments/files/16134950/crash-2024-07-08_18.19.16-client.txt)
[crash-2024-07-08_18.17.34-client.txt](https://github.com/user-attachments/files/16135005/crash-2024-07-08_18.17.34-client.txt)

**Comment by Jeryn99** [comment]
Fixed, please download 1.0.6
