### ISSUE TITLE
Fabric Server Crashes on Launch

### ISSUE THREAD

**Issue by aatkraus** [Suff99/ExtraShells#7]
I'm running a Fabric 1.20.2 server with TARDIS Refined  and ExtraShells on Fabric Modloader 0.16.5. The client runs perfectly fine with the same mods, but the server crashes on startup. I'd appreciate any help you can provide, thanks!

[latest.log](https://github.com/user-attachments/files/17137980/latest.log)

**Comment by Jeryn99** [comment]
<del>Extrashells is crashing your server on Fabric, I will investigate this when I can

<del>But I will be closing this issue, please move it to the correct repository 

<del>https://github.com/Jeryn99/ExtraShells/issues

**Comment by Jeryn99** [comment]
I am a idiot and misread this, I thought this was the TR repo lol whoopsies

**Comment by Jeryn99** [comment]
Download 1.0.8 from modrinth <3

**Comment by aatkraus** [comment]
That was fast! Thank you so much!
